// ── Music notes ───────────────────────────────────────────────────────────────
export const NOTE_COUNT = 4
export const NOTE_LIFETIME = 5.2
export const NOTE_SIZE = 0.65
export const NOTE_SIZE_VARIANCE = 0.2
export const NOTE_RISE = 1.5
export const NOTE_SPREAD = 0.3
export const NOTE_SWAY = 0.25
export const NOTE_SWAY_RATE = 6
export const NOTE_POP_SECONDS = 0.35
export const NOTE_POP_OVERSHOOT = 0.35
export const NOTE_FADE_FROM = 0.7
export const NOTE_TILT = 0.3
export const NOTE_TILT_RATE = 6
export const NOTE_COLOR = '#fff3d6'
export const NOTE_OUTLINE_COLOR = '#3b2418'
export const NOTE_OUTLINE_WIDTH = 6
export const NOTE_ATLAS_CELL = 128
